springdoc:
  show-login-endpoint: true

spring:
  profiles:
    active: prod

  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: ${spring.datasource.driver-class-name}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace

solapi:
  apiKey: ${SOLAPI_APIKEY}
  secretkey: ${SOLAPI_SECRETKEY}

jwt:
  header: ${HEADER}
  secret: ${SECRET-KEY}
  expiration: ${EXPIRATION} # 1시간
  refresh-token-expiration: ${REFRESH-EXPIRATION} # 7일

kakao:
  local:
    base-url: https://dapi.kakao.com
    rest-api-key: ${KAKAO_REST_API_KEY}

cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET}
    stack.auto: false
    region.static: ${AWS_REGION}
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}

gpt:
  api:
    key: ${GPT_API_KEY}
    url: https://api.openai.com/v1/chat/completions
  model: gpt-4o-mini